package domain

// ConfigSchema returns the complete catalog of all 94 environment variables
// managed by the Control Plane.
//
// Categories:
//   - StaticDefault  (36): same value across all projects
//   - PerProject     (16): computed or allocated per project
//   - GeneratedSecret (12): generated per project at creation time
//   - UserOverridable (30): have defaults but can be overridden by the user
func ConfigSchema() []ConfigEntry {
	return []ConfigEntry{

		// ── StaticDefault (36) ────────────────────────────────────────────
		{Key: "POSTGRES_HOST", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "db",
			Description:  "Docker service name for the PostgreSQL container",
			Services:     []ServiceName{ServiceAuth, ServiceRest, ServiceRealtime, ServiceStorage, ServiceMeta, ServiceAnalytics, ServiceSupavisor}},
		{Key: "POSTGRES_DB", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "postgres",
			Description:  "Default database name",
			Services:     []ServiceName{ServiceAuth, ServiceRest, ServiceRealtime, ServiceStorage, ServiceMeta, ServiceAnalytics, ServiceSupavisor}},
		{Key: "GOTRUE_API_HOST", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "0.0.0.0",
			Description:  "GoTrue listen address (all interfaces)",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "GOTRUE_API_PORT", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "9999",
			Description:  "GoTrue internal port",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "GOTRUE_DB_DRIVER", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "postgres",
			Description:  "GoTrue database driver",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "GOTRUE_JWT_ADMIN_ROLES", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "service_role",
			Description:  "JWT roles treated as admin",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "GOTRUE_JWT_AUD", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "authenticated",
			Description:  "JWT audience claim",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "GOTRUE_JWT_DEFAULT_GROUP_NAME", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "authenticated",
			Description:  "Default group for new users",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "PGRST_DB_ANON_ROLE", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "anon",
			Description:  "PostgREST anonymous database role",
			Services:     []ServiceName{ServiceRest}},
		{Key: "PGRST_DB_USE_LEGACY_GUCS", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "false",
			Description:  "Disable legacy PostgREST GUC settings",
			Services:     []ServiceName{ServiceRest}},
		{Key: "KONG_DATABASE", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "off",
			Description:  "Kong database-less mode",
			Services:     []ServiceName{ServiceKong}},
		{Key: "KONG_DNS_ORDER", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "LAST,A,CNAME",
			Description:  "Kong DNS resolution order",
			Services:     []ServiceName{ServiceKong}},
		{Key: "KONG_DNS_NOT_FOUND_TTL", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "1",
			Description:  "Kong DNS cache TTL for not-found responses",
			Services:     []ServiceName{ServiceKong}},
		{Key: "DB_AFTER_CONNECT_QUERY", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "SET search_path TO _realtime",
			Description:  "SQL executed after Realtime DB connect",
			Services:     []ServiceName{ServiceRealtime}},
		{Key: "DB_ENC_KEY", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "supabaserealtime",
			Description:  "Realtime encryption key (TODO: Phase 2 — make per-project GeneratedSecret)",
			Services:     []ServiceName{ServiceRealtime}},
		{Key: "ERL_AFLAGS", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "-proto_dist inet_tcp",
			Description:  "Erlang TCP distribution protocol flags",
			Services:     []ServiceName{ServiceRealtime, ServiceSupavisor}},
		{Key: "APP_NAME", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "realtime",
			Description:  "Realtime application name",
			Services:     []ServiceName{ServiceRealtime}},
		{Key: "SEED_SELF_HOST", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Realtime auto-creates tenant on startup",
			Services:     []ServiceName{ServiceRealtime}},
		{Key: "RUN_JANITOR", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Realtime runs automatic cleanup",
			Services:     []ServiceName{ServiceRealtime}},
		{Key: "STORAGE_BACKEND", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "file",
			Description:  "Storage backend type",
			Services:     []ServiceName{ServiceStorage}},
		{Key: "FILE_SIZE_LIMIT", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "52428800",
			Description:  "Storage upload size limit (50 MB)",
			Services:     []ServiceName{ServiceStorage}},
		{Key: "ENABLE_IMAGE_TRANSFORMATION", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Enable imgproxy image transformation in storage",
			Services:     []ServiceName{ServiceStorage}},
		{Key: "IMGPROXY_LOCAL_FILESYSTEM_ROOT", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "/",
			Description:  "imgproxy local filesystem root",
			Services:     []ServiceName{ServiceImgProxy}},
		{Key: "IMGPROXY_USE_ETAG", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Enable ETag caching in imgproxy",
			Services:     []ServiceName{ServiceImgProxy}},
		{Key: "LOGFLARE_NODE_HOST", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "127.0.0.1",
			Description:  "Logflare node host address",
			Services:     []ServiceName{ServiceAnalytics}},
		{Key: "DB_SCHEMA", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "_analytics",
			Description:  "Analytics database schema",
			Services:     []ServiceName{ServiceAnalytics}},
		{Key: "LOGFLARE_SINGLE_TENANT", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Run Logflare in single-tenant mode",
			Services:     []ServiceName{ServiceAnalytics}},
		{Key: "LOGFLARE_SUPABASE_MODE", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Enable Supabase mode in Logflare",
			Services:     []ServiceName{ServiceAnalytics}},
		{Key: "CLUSTER_POSTGRES", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Supavisor uses Postgres for cluster state",
			Services:     []ServiceName{ServiceSupavisor}},
		{Key: "REGION", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "local",
			Description:  "Region identifier for storage and supavisor",
			Services:     []ServiceName{ServiceStorage, ServiceSupavisor}},
		{Key: "POOLER_POOL_MODE", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "transaction",
			Description:  "Supavisor connection pool mode",
			Services:     []ServiceName{ServiceSupavisor}},
		{Key: "NEXT_PUBLIC_ENABLE_LOGS", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Enable logs in Studio",
			Services:     []ServiceName{ServiceStudio}},
		{Key: "NEXT_ANALYTICS_BACKEND_PROVIDER", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "postgres",
			Description:  "Studio analytics backend provider",
			Services:     []ServiceName{ServiceStudio}},
		{Key: "HOSTNAME", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "::",
			Description:  "Studio bind address (IPv4+IPv6)",
			Services:     []ServiceName{ServiceStudio}},
		{Key: "DISABLE_HEALTHCHECK_LOGGING", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Suppress health check log noise in Realtime",
			Services:     []ServiceName{ServiceRealtime}},
		{Key: "REQUEST_ALLOW_X_FORWARDED_PATH", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Allow X-Forwarded-Path header in Storage",
			Services:     []ServiceName{ServiceStorage}},

		// ── PerProject (13) ───────────────────────────────────────────────
		{Key: "KONG_HTTP_PORT", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "External API port (allocated starting from 28081)",
			Services:    []ServiceName{ServiceKong},
			Required:    true},
		{Key: "KONG_HTTPS_PORT", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "External HTTPS port (derived: KONG_HTTP_PORT + 1)",
			Services:    []ServiceName{ServiceKong},
			Required:    true},
		{Key: "POSTGRES_PORT", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "PostgreSQL port (allocated starting from 54320)",
			Services:    []ServiceName{ServiceDB, ServiceSupavisor, ServiceAuth, ServiceRest, ServiceRealtime, ServiceStorage, ServiceMeta, ServiceAnalytics},
			Required:    true},
		{Key: "POOLER_PROXY_PORT_TRANSACTION", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "Supavisor transaction port (allocated starting from 64300)",
			Services:    []ServiceName{ServiceSupavisor},
			Required:    true},
		{Key: "API_EXTERNAL_URL", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "External API URL: http://localhost:${KONG_HTTP_PORT}",
			Services:    []ServiceName{ServiceAuth},
			Required:    true},
		{Key: "SUPABASE_PUBLIC_URL", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "Public Supabase URL: http://localhost:${KONG_HTTP_PORT}",
			Services:    []ServiceName{ServiceStorage, ServiceFunctions, ServiceStudio},
			Required:    true},
		{Key: "SITE_URL", Category: CategoryPerProject, Scope: ScopeProject,
			DefaultValue: "http://localhost:3000",
			Description:  "Frontend redirect URL for auth callbacks",
			Services:     []ServiceName{ServiceAuth},
			Required:     true},
		{Key: "PROJECT_DATA_DIR", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "Project data volume directory relative to the project directory: ./volumes",
			Services:    []ServiceName{ServiceStudio, ServiceStorage, ServiceImgProxy, ServiceDB, ServiceFunctions},
			Required:    true},
		{Key: "STUDIO_DEFAULT_ORGANIZATION", Category: CategoryPerProject, Scope: ScopeProject,
			DefaultValue: "Default Organization",
			Description:  "Studio default organization display name",
			Services:     []ServiceName{ServiceStudio}},
		{Key: "STUDIO_DEFAULT_PROJECT", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "Studio default project name (set to DisplayName)",
			Services:    []ServiceName{ServiceStudio}},
		{Key: "STORAGE_TENANT_ID", Category: CategoryPerProject, Scope: ScopeProject,
			DefaultValue: "stub",
			Description:  "Storage tenant identifier (Phase 1 stub; Phase 2 will derive from SLUG)",
			Services:     []ServiceName{ServiceStorage}},
		{Key: "POOLER_TENANT_ID", Category: CategoryPerProject, Scope: ScopeProject,
			Description: "Supavisor tenant identifier (set to project slug)",
			Services:    []ServiceName{ServiceSupavisor},
			Required:    true},
		{Key: "DOCKER_SOCKET_LOCATION", Category: CategoryPerProject, Scope: ScopeProject,
			DefaultValue: "/var/run/docker.sock",
			Description:  "Docker socket path for Vector (TODO: Phase 2 — evaluate UserOverridable)",
			Services:     []ServiceName{ServiceVector}},
		// PG_META_PORT and IMGPROXY_BIND are StaticDefault because they are internal
		// container ports that do not need to be unique across projects — each project
		// runs in its own isolated Docker network.
		{Key: "PG_META_PORT", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: "8080",
			Description:  "pg-meta internal listen port (static; each project has its own Docker network)",
			Services:     []ServiceName{ServiceMeta, ServiceStudio}},
		{Key: "IMGPROXY_BIND", Category: CategoryStaticDefault, Scope: ScopeProject,
			DefaultValue: ":5001",
			Description:  "imgproxy internal bind address (static; each project has its own Docker network)",
			Services:     []ServiceName{ServiceImgProxy}},

		// ── GeneratedSecret (12) ─────────────────────────────────────────
		{Key: "JWT_SECRET", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "JWT signing secret (64-char hex random)",
			Services:    []ServiceName{ServiceAuth, ServiceRest, ServiceRealtime, ServiceStorage, ServiceFunctions, ServiceSupavisor, ServiceDB},
			Sensitive:   true, Required: true},
		{Key: "ANON_KEY", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Public API key JWT (role=anon, signed with JWT_SECRET)",
			Services:    []ServiceName{ServiceKong, ServiceStorage, ServiceFunctions, ServiceStudio},
			Sensitive:   true, Required: true},
		{Key: "SERVICE_ROLE_KEY", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Admin API key JWT (role=service_role, signed with JWT_SECRET)",
			Services:    []ServiceName{ServiceKong, ServiceStorage, ServiceFunctions, ServiceStudio},
			Sensitive:   true, Required: true},
		{Key: "POSTGRES_PASSWORD", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "PostgreSQL password (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceDB, ServiceAuth, ServiceRest, ServiceRealtime, ServiceStorage, ServiceMeta, ServiceAnalytics, ServiceSupavisor},
			Sensitive:   true, Required: true},
		{Key: "DASHBOARD_PASSWORD", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Studio dashboard login password (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceKong},
			Sensitive:   true, Required: true},
		{Key: "SECRET_KEY_BASE", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Phoenix session key for Realtime and Supavisor (64-char hex random)",
			Services:    []ServiceName{ServiceRealtime, ServiceSupavisor},
			Sensitive:   true, Required: true},
		{Key: "VAULT_ENC_KEY", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Vault encryption key for Supavisor (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceSupavisor},
			Sensitive:   true, Required: true},
		{Key: "PG_META_CRYPTO_KEY", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "pg-meta and Studio encryption key (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceMeta, ServiceStudio},
			Sensitive:   true, Required: true},
		{Key: "LOGFLARE_PUBLIC_ACCESS_TOKEN", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Logflare public access token (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceAnalytics, ServiceStudio, ServiceVector},
			Sensitive:   true, Required: true},
		{Key: "LOGFLARE_PRIVATE_ACCESS_TOKEN", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "Logflare private access token (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceAnalytics, ServiceStudio},
			Sensitive:   true, Required: true},
		{Key: "S3_PROTOCOL_ACCESS_KEY_ID", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "S3 protocol access key ID (32-char alphanumeric random)",
			Services:    []ServiceName{ServiceStorage},
			Sensitive:   true, Required: true},
		{Key: "S3_PROTOCOL_ACCESS_KEY_SECRET", Category: CategoryGeneratedSecret, Scope: ScopeProject,
			Description: "S3 protocol access key secret (64-char alphanumeric random)",
			Services:    []ServiceName{ServiceStorage},
			Sensitive:   true, Required: true},

		// ── UserOverridable (30) ─────────────────────────────────────────
		{Key: "PGRST_DB_SCHEMAS", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "public,storage,graphql_public",
			Description:  "PostgREST exposed database schemas",
			Services:     []ServiceName{ServiceRest, ServiceStudio}},
		{Key: "PGRST_DB_MAX_ROWS", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "1000",
			Description:  "PostgREST maximum rows returned per request",
			Services:     []ServiceName{ServiceRest, ServiceStudio}},
		{Key: "PGRST_DB_EXTRA_SEARCH_PATH", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "public",
			Description:  "PostgREST additional search path",
			Services:     []ServiceName{ServiceRest}},
		{Key: "ADDITIONAL_REDIRECT_URLS", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "",
			Description:  "Additional allowed redirect URLs for auth",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "DISABLE_SIGNUP", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "false",
			Description:  "Disable new user sign-ups",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "ENABLE_EMAIL_SIGNUP", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Enable email/password sign-up",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "ENABLE_ANONYMOUS_USERS", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "false",
			Description:  "Enable anonymous user sessions",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "ENABLE_EMAIL_AUTOCONFIRM", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Auto-confirm email addresses on sign-up",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "ENABLE_PHONE_SIGNUP", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Enable phone number sign-up",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "ENABLE_PHONE_AUTOCONFIRM", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Auto-confirm phone numbers on sign-up",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "SMTP_ADMIN_EMAIL", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "admin@example.com",
			Description:  "SMTP sender email address",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "SMTP_HOST", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "supabase-mail",
			Description:  "SMTP server hostname",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "SMTP_PORT", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "2500",
			Description:  "SMTP server port",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "SMTP_USER", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "fake_mail_user",
			Description:  "SMTP authentication username",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "SMTP_PASS", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "fake_mail_password",
			Description:  "SMTP authentication password",
			Services:     []ServiceName{ServiceAuth},
			Sensitive:    true},
		{Key: "SMTP_SENDER_NAME", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "fake_sender",
			Description:  "SMTP sender display name",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "MAILER_URLPATHS_INVITE", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "/auth/v1/verify",
			Description:  "URL path for invitation emails",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "MAILER_URLPATHS_CONFIRMATION", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "/auth/v1/verify",
			Description:  "URL path for confirmation emails",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "MAILER_URLPATHS_RECOVERY", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "/auth/v1/verify",
			Description:  "URL path for password recovery emails",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "MAILER_URLPATHS_EMAIL_CHANGE", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "/auth/v1/verify",
			Description:  "URL path for email change confirmation",
			Services:     []ServiceName{ServiceAuth}},
		{Key: "FUNCTIONS_VERIFY_JWT", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "false",
			Description:  "Require JWT verification for Edge Functions",
			Services:     []ServiceName{ServiceFunctions}},
		{Key: "IMGPROXY_AUTO_WEBP", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "true",
			Description:  "Automatically convert images to WebP",
			Services:     []ServiceName{ServiceImgProxy}},
		{Key: "IMGPROXY_MAX_SRC_RESOLUTION", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "16.8",
			Description:  "Maximum source image resolution for imgproxy",
			Services:     []ServiceName{ServiceImgProxy}},
		{Key: "GLOBAL_S3_BUCKET", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "stub",
			Description:  "S3 bucket name for storage",
			Services:     []ServiceName{ServiceStorage}},
		{Key: "OPENAI_API_KEY", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "",
			Description:  "OpenAI API key for Studio AI features",
			Services:     []ServiceName{ServiceStudio},
			Sensitive:    true},
		{Key: "POOLER_DEFAULT_POOL_SIZE", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "20",
			Description:  "Supavisor default connection pool size",
			Services:     []ServiceName{ServiceSupavisor}},
		{Key: "POOLER_MAX_CLIENT_CONN", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "100",
			Description:  "Supavisor maximum client connections",
			Services:     []ServiceName{ServiceSupavisor}},
		{Key: "POOLER_DB_POOL_SIZE", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "5",
			Description:  "Supavisor DB connection pool size",
			Services:     []ServiceName{ServiceSupavisor}},
		{Key: "JWT_EXPIRY", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "3600",
			Description:  "JWT token expiry in seconds",
			Services:     []ServiceName{ServiceAuth, ServiceRest, ServiceDB}},
		{Key: "DASHBOARD_USERNAME", Category: CategoryUserOverridable, Scope: ScopeProject,
			DefaultValue: "supabase",
			Description:  "Studio dashboard login username",
			Services:     []ServiceName{ServiceKong}},
	}
}
