version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosimple

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

issues:
  exclude-dirs:
    - vendor
